#- platform: openweathermap
#  api_key: e11d11775f1edba3b409538d9686d243
#  latitude: 43.1056200
#  longitude: 131.8735300
#  monitored_conditions:
#    - weather
#    - temperature
#    - wind_speed
#    - humidity
#    - clouds
#    - rain
#    - snow
#  customize:
#    hidden: true
    
- platform: yweather
  monitored_conditions:
    - humidity
    - temperature
  